version: '2'

volumes:
  peer0.org3.example.com:

networks:
  net:

services:

  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/

  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:10051
      - CORE_PEER_LOCALMSPID=org3
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ../fixtures/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
      - ../fixtures/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org3.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053
    networks:
      - net

  cli.org3.example.com:
    container_name: cli.org3.example.com
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:10051
      - CORE_PEER_LOCALMSPID=org3
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/chaincode
      - ../../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../fixtures/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../fixtures/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/fixtures/channel-artifacts
      - ../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/bin
    depends_on:
      - peer0.org3.example.com
    networks:
      - net