Organizations:

  - &org1
    Name: org1
    ID: org1
    MSPDir: ../../fixtures/organizations/peerOrganizations/org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org1.admin', 'org1.peer', 'org1.client')"
      Writers:
        Type: Signature
        Rule: "OR('org1.admin', 'org1.client')"
      Admins:
        Type: Signature
        Rule: "OR('org1.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('org1.peer')"
    AnchorPeers:
      - Host: peer0.org1.example.com
        Port: 8051
