Organizations:

  - &org2
    Name: org2
    ID: org2
    MSPDir: ../../fixtures/organizations/peerOrganizations/org2.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org2.admin', 'org2.peer', 'org2.client')"
      Writers:
        Type: Signature
        Rule: "OR('org2.admin', 'org2.client')"
      Admins:
        Type: Signature
        Rule: "OR('org2.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('org2.peer')"
    AnchorPeers:
      - Host: peer0.org2.example.com
        Port: 9051
